@extends("layouts.site_layout.app")
@section('content')
    <body>
        <ul>
            <li>    
                {{$data['id']}}
            </li>
            <li>
                {{$data['title']}}
            </li>
            <li>
                {{$data['description']}}
            </li>
        </ul>
@endsection